//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 03:06:45 PM MYT 
//


package com.azrul.langkuik.framework.workflow.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseActivity">
 *   &lt;complexContent>
 *     &lt;extension base="{}Activity">
 *       &lt;choice>
 *         &lt;element name="preRunScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postRunScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="next" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseActivity", propOrder = {
    "preRunScript",
    "postRunScript"
})
@XmlSeeAlso({
    StartEvent.class,
    HumanActivity.class,
    ServiceActivity.class
})
public abstract class BaseActivity
    extends Activity
{

    protected String preRunScript;
    protected String postRunScript;
    @XmlAttribute(name = "next")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object next;

    /**
     * Gets the value of the preRunScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreRunScript() {
        return preRunScript;
    }

    /**
     * Sets the value of the preRunScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreRunScript(String value) {
        this.preRunScript = value;
    }

    /**
     * Gets the value of the postRunScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostRunScript() {
        return postRunScript;
    }

    /**
     * Sets the value of the postRunScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostRunScript(String value) {
        this.postRunScript = value;
    }

    /**
     * Gets the value of the next property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNext() {
        return next;
    }

    /**
     * Sets the value of the next property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNext(Object value) {
        this.next = value;
    }

}
