//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 03:06:45 PM MYT 
//


package com.azrul.langkuik.framework.workflow.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.azrul.langkuik.framework.workflow.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.azrul.langkuik.framework.workflow.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BizProcess }
     * 
     */
    public BizProcess createBizProcess() {
        return new BizProcess();
    }

    /**
     * Create an instance of {@link BizProcess.Workflow }
     * 
     */
    public BizProcess.Workflow createBizProcessWorkflow() {
        return new BizProcess.Workflow();
    }

    /**
     * Create an instance of {@link DefaultBranch }
     * 
     */
    public DefaultBranch createDefaultBranch() {
        return new DefaultBranch();
    }

    /**
     * Create an instance of {@link ConditionalBranch }
     * 
     */
    public ConditionalBranch createConditionalBranch() {
        return new ConditionalBranch();
    }

    /**
     * Create an instance of {@link TieBreakerBranch }
     * 
     */
    public TieBreakerBranch createTieBreakerBranch() {
        return new TieBreakerBranch();
    }

    /**
     * Create an instance of {@link RejectedBranch }
     * 
     */
    public RejectedBranch createRejectedBranch() {
        return new RejectedBranch();
    }

    /**
     * Create an instance of {@link ApprovedBranch }
     * 
     */
    public ApprovedBranch createApprovedBranch() {
        return new ApprovedBranch();
    }

    /**
     * Create an instance of {@link XorUnanimousApprovalActivity }
     * 
     */
    public XorUnanimousApprovalActivity createXorUnanimousApprovalActivity() {
        return new XorUnanimousApprovalActivity();
    }

    /**
     * Create an instance of {@link HumanActivity }
     * 
     */
    public HumanActivity createHumanActivity() {
        return new HumanActivity();
    }

    /**
     * Create an instance of {@link XorAtleastOneApprovalActivity }
     * 
     */
    public XorAtleastOneApprovalActivity createXorAtleastOneApprovalActivity() {
        return new XorAtleastOneApprovalActivity();
    }

    /**
     * Create an instance of {@link StartEvent }
     * 
     */
    public StartEvent createStartEvent() {
        return new StartEvent();
    }

    /**
     * Create an instance of {@link XorMajorityApprovalActivity }
     * 
     */
    public XorMajorityApprovalActivity createXorMajorityApprovalActivity() {
        return new XorMajorityApprovalActivity();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link ServiceActivity }
     * 
     */
    public ServiceActivity createServiceActivity() {
        return new ServiceActivity();
    }

    /**
     * Create an instance of {@link XorActivity }
     * 
     */
    public XorActivity createXorActivity() {
        return new XorActivity();
    }

}
