//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 03:06:45 PM MYT 
//


package com.azrul.langkuik.framework.workflow.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StartEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StartEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseActivity">
 *       &lt;attribute name="canBeStartedBy" use="required" type="{}StringArray" />
 *       &lt;attribute name="supervisoryApprovalHierarchy" type="{}StringArray" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StartEvent")
public class StartEvent
    extends BaseActivity
{

    @XmlAttribute(name = "canBeStartedBy", required = true)
    protected List<String> canBeStartedBy;
    @XmlAttribute(name = "supervisoryApprovalHierarchy")
    protected List<String> supervisoryApprovalHierarchy;

    /**
     * Gets the value of the canBeStartedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the canBeStartedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCanBeStartedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCanBeStartedBy() {
        if (canBeStartedBy == null) {
            canBeStartedBy = new ArrayList<String>();
        }
        return this.canBeStartedBy;
    }

    /**
     * Gets the value of the supervisoryApprovalHierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supervisoryApprovalHierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupervisoryApprovalHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupervisoryApprovalHierarchy() {
        if (supervisoryApprovalHierarchy == null) {
            supervisoryApprovalHierarchy = new ArrayList<String>();
        }
        return this.supervisoryApprovalHierarchy;
    }

}
