//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 03:06:45 PM MYT 
//


package com.azrul.langkuik.framework.workflow.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XorActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XorActivity">
 *   &lt;complexContent>
 *     &lt;extension base="{}Activity">
 *       &lt;sequence>
 *         &lt;element name="byDefault" type="{}DefaultBranch"/>
 *         &lt;element name="branch" type="{}ConditionalBranch" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XorActivity", propOrder = {
    "byDefault",
    "branch"
})
public class XorActivity
    extends Activity
{

    @XmlElement(required = true)
    protected DefaultBranch byDefault;
    @XmlElement(required = true)
    protected List<ConditionalBranch> branch;

    /**
     * Gets the value of the byDefault property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultBranch }
     *     
     */
    public DefaultBranch getByDefault() {
        return byDefault;
    }

    /**
     * Sets the value of the byDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultBranch }
     *     
     */
    public void setByDefault(DefaultBranch value) {
        this.byDefault = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the branch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBranch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConditionalBranch }
     * 
     * 
     */
    public List<ConditionalBranch> getBranch() {
        if (branch == null) {
            branch = new ArrayList<ConditionalBranch>();
        }
        return this.branch;
    }

}
