//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 03:06:45 PM MYT 
//


package com.azrul.langkuik.framework.workflow.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XorApprovalActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XorApprovalActivity">
 *   &lt;complexContent>
 *     &lt;extension base="{}HumanActivity">
 *       &lt;sequence>
 *         &lt;element name="byDefault" type="{}DefaultBranch"/>
 *         &lt;element name="onApproved" type="{}ApprovedBranch" maxOccurs="unbounded"/>
 *         &lt;element name="onRejected" type="{}RejectedBranch" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XorApprovalActivity", propOrder = {
    "byDefault",
    "onApproved",
    "onRejected"
})
@XmlSeeAlso({
    XorUnanimousApprovalActivity.class,
    XorAtleastOneApprovalActivity.class,
    XorMajorityApprovalActivity.class
})
public abstract class XorApprovalActivity
    extends HumanActivity
{

    @XmlElement(required = true)
    protected DefaultBranch byDefault;
    @XmlElement(required = true)
    protected List<ApprovedBranch> onApproved;
    protected List<RejectedBranch> onRejected;

    /**
     * Gets the value of the byDefault property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultBranch }
     *     
     */
    public DefaultBranch getByDefault() {
        return byDefault;
    }

    /**
     * Sets the value of the byDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultBranch }
     *     
     */
    public void setByDefault(DefaultBranch value) {
        this.byDefault = value;
    }

    /**
     * Gets the value of the onApproved property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onApproved property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnApproved().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApprovedBranch }
     * 
     * 
     */
    public List<ApprovedBranch> getOnApproved() {
        if (onApproved == null) {
            onApproved = new ArrayList<ApprovedBranch>();
        }
        return this.onApproved;
    }

    /**
     * Gets the value of the onRejected property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onRejected property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnRejected().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RejectedBranch }
     * 
     * 
     */
    public List<RejectedBranch> getOnRejected() {
        if (onRejected == null) {
            onRejected = new ArrayList<RejectedBranch>();
        }
        return this.onRejected;
    }

}
