//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.27 at 03:06:45 PM MYT 
//


package com.azrul.langkuik.framework.workflow.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XorMajorityApprovalActivity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XorMajorityApprovalActivity">
 *   &lt;complexContent>
 *     &lt;extension base="{}XorApprovalActivity">
 *       &lt;sequence>
 *         &lt;element name="onTieBreaker" type="{}TieBreakerBranch"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XorMajorityApprovalActivity", propOrder = {
    "onTieBreaker"
})
public class XorMajorityApprovalActivity
    extends XorApprovalActivity
{

    @XmlElement(required = true)
    protected TieBreakerBranch onTieBreaker;

    /**
     * Gets the value of the onTieBreaker property.
     * 
     * @return
     *     possible object is
     *     {@link TieBreakerBranch }
     *     
     */
    public TieBreakerBranch getOnTieBreaker() {
        return onTieBreaker;
    }

    /**
     * Sets the value of the onTieBreaker property.
     * 
     * @param value
     *     allowed object is
     *     {@link TieBreakerBranch }
     *     
     */
    public void setOnTieBreaker(TieBreakerBranch value) {
        this.onTieBreaker = value;
    }

}
