INSERT INTO public.relationshipmanager VALUES (93, 'glory.bee', 2,NULL,NULL, 'loanorigsystem',  'END', NULL,NULL,'Alister', 'S1000001', 'McNeil');
INSERT INTO public.relationshipmanager VALUES (96, 'glory.bee', 2,NULL,NULL, 'loanorigsystem', 'END',NULL,NULL, 'Jonathan', 'S1000004', 'Hollis');
INSERT INTO public.relationshipmanager VALUES (95, 'glory.bee', 2,NULL,NULL, 'loanorigsystem',  'END',NULL,NULL, 'Alexandra', 'S1000003', 'Cullen');
INSERT INTO public.relationshipmanager VALUES (94, 'glory.bee', 2,NULL,NULL, 'loanorigsystem', 'END', NULL,NULL,'Connor', 'S1000002', 'Levine');
INSERT INTO public.relationshipmanager VALUES (1107, 'glory.bee',2,NULL,NULL, 'loanorigsystem', 'END', NULL, NULL,'Harry', 'S1000011', 'Young');
INSERT INTO public.relationshipmanager VALUES (1108, 'glory.bee',2,NULL,NULL, 'loanorigsystem', 'END', NULL, NULL,'Henry', 'S0000011', 'Young');
INSERT INTO public.relationshipmanager VALUES (1109, 'glory.bee',2,NULL,NULL, 'loanorigsystem', 'END', NULL,NULL,'Henry', 'S1000011', 'Johnson');
INSERT INTO public.relationshipmanager VALUES (1113, 'glory.bee', 2,NULL,NULL, 'loanorigsystem',  'END', NULL,NULL,'Henry', 'S1000011', 'Johnson');
INSERT INTO public.relationshipmanager VALUES (1228, 'glory.bee',2,NULL,NULL, 'loanorigsystem',  'END', NULL,NULL,'Jimmy', 'S1000', 'Larson');
insert into public.element_owners (element_id, owners) VALUES (	93	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	94	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	95	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	96	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	1107	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	1108	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	1109	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	1113	,'glory.bee');
insert into public.element_owners (element_id, owners) VALUES (	1228	,'glory.bee');